- .github/workflows/release.yml
- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/helm-controller.yaml
- charts/flux2/templates/image-automation-controller.yaml
- charts/flux2/templates/image-reflector-controller.yaml
- charts/flux2/templates/kustomize-controller.yaml
- charts/flux2/templates/notification-controller.yaml
- charts/flux2/templates/source-controller.yaml
- charts/flux2/values.yaml
You are able to add custom annotation, labes and resources limits for cpu and memory,
Furthermore there is an addition to mount secrets in kustomize-controller so it can access private repos with creds when its used without source-controller.
> extend configurable values for resources, annotations and mounts

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/image-automation-controller.yaml
- charts/flux2/templates/image-reflector-controller.yaml
- charts/flux2/templates/kustomize-controller.yaml
- charts/flux2/templates/notification-controller.yaml
- charts/flux2/templates/source-controller.yaml
Labels are set correctly on the pods now. Before there was a yaml syntax error in some cases.
- fixes #19
> fix labels on pods

- charts/flux2/Chart.yaml
- charts/flux2/templates/notification-controller.yaml
Remove duplicated key 'metadata' in notification controller
- fixes #
> Remove duplicated key 'metadata'

- .github/workflows/e2e-sync.yaml
- .github/workflows/lint-test.yaml
> Add uninstall to e2e test suite

- charts/flux2-sync/Chart.yaml
- charts/flux2-sync/README.md
- charts/flux2-sync/templates/gitrepository.yaml
- charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap
Current flux2-sync (0.3.0) chart throws error if you specify a `gitRepository.spec.secretRef.name` value and `secret.create` is set to false.
helm error message:
```sh
helm upgrade --install flux2-sync fluxcd-community/flux2-sync -n default -f values.yaml
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(GitRepository.spec.secretRef): unknown field "Capabilities" in io.fluxcd.toolkit.source.v1beta1.GitRepository.spec.secretRef, ValidationError(GitRepository.spec.secretRef): unknown field "Chart" in io.fluxcd.toolkit.source.v1beta1.GitRepository.spec.secretRef, ValidationError(GitRepository.spec.secretRef): unknown field "Files" in io.fluxcd.toolkit.source.v1beta1.GitRepository.spec.secretRef, ValidationError(GitRepository.spec.secretRef): unknown field …
```
> Fix bug in secretRef value

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/kustomize-controller.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
Signed-off-by: MxNxPx <MxNxPx@gmail.com>
- Allow for the ability to specify envFrom values for the kustomize controller
- Required namely when using an Azure service principal to decrypt sops encrypted secrets
- fixes #
https://github.com/fluxcd-community/helm-charts/issues/35
> Add option to specify envFrom for kustomize controller

- Makefile
- charts/flux2-sync/Chart.yaml
- charts/flux2-sync/README.md
- charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/helm-controller.crds.yaml
- charts/flux2/templates/image-automation-controller.crds.yaml
- charts/flux2/templates/image-reflector-controller.crds.yaml
- charts/flux2/templates/kustomize-controller.crds.yaml
- charts/flux2/templates/notification-controller.crds.yaml
- charts/flux2/templates/source-controller.crds.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
- hack/generate.sh
- bump upstream flux 0.24.0 to 0.24.1
- added generator to get all crds, add our lables, add if block
- added make generate
- added make helmdocs
- added make check-diff  
- as followup we should add in ci generate,helmdocs,check-diff then we can check that all needed steps are executed in the commit
- as followup we should generate version in Chart.yaml 
- as followup we should generate imagetags from upstream
- as followup we should generate version, chartVersion, imagetag in all testfiles
- generator.sh uses FLUX2_VERSION out of Makefile
```
make generate
09:06:34 [ .. ] Fetch Flux2 GitRepo
HEAD ist jetzt bei ff7df54 Merge pull request #2178 from fluxcd/update-components
09:06:35 [ OK ] Fetch Flux2 GitRepo
09:06:35 [ .. ] Generating …
```
> feat(0.24.1) added generator and bumped 0.24.0 to 0.24.1

- .github/PULL_REQUEST_TEMPLATE.md
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Makefile
- README.md
- _readme_templates.gotmpl
- charts/flux2-multi-tenancy/Chart.yaml
- charts/flux2-multi-tenancy/README.md
- charts/flux2-multi-tenancy/tests/__snapshot__/kyverno-policy_test.yaml.snap
- charts/flux2-multi-tenancy/tests/kyverno-policy_test.yaml
- charts/flux2-sync/Chart.yaml
- charts/flux2-sync/README.md
- charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- hack/generate.sh
- Add unittest for flux2-multi-tenancy chart
- Add _readme_templates.gotmpl to adjust generated READMEs, and add hint, that the charts are community driven. 
- Extend Makefile, so you can run `make reviewable` and see if everything is fine before opening the PR
- fixes #27
> chore: update Makefile and Readme

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/helm-controller.yaml
- charts/flux2/templates/image-automation-controller.yaml
- charts/flux2/templates/image-reflector-controller.yaml
- charts/flux2/templates/kustomize-controller.yaml
- charts/flux2/templates/notification-controller.yaml
- charts/flux2/templates/source-controller.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
Example helm cli usage to provide an imagePullSecret
```
helm ... --set "imagePullSecrets[0].name=secret1"
```
Signed-off-by: Robert R Allen <robert.r.allen@ericsson.com>
The flux CLI supports customizing the imagePullSecrets. This brings equivalent behavior to the helm chart.
- partially implements #53
> support setting of imagePullSecrets for all controllers #53

- Makefile
- hack/generate.sh
- `make generate` will also bump chart version if needed.
- Add `make help`
- fixes #48
> chore: add update.chartversion Makefile and help

- Makefile
- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/helm-controller.crds.yaml
- charts/flux2/templates/image-automation-controller.crds.yaml
- charts/flux2/templates/image-reflector-controller.crds.yaml
- charts/flux2/templates/kustomize-controller.crds.yaml
- charts/flux2/templates/notification-controller.crds.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
update to flux2 upstream v0.25.3 release
https://github.com/fluxcd/flux2/releases/tag/v0.25.3
`This will be the last version where flux2 upstream support Kubernetes 1.19 and older. Next release will drop all EOL versions and it will come with a restricted pod security profile.`
> feat(v0.25.3): bump for upstream release flux2 to v0.25.3

- .github/PULL_REQUEST_TEMPLATE.md
- Makefile
- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/extra-manifests.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/tests/extra-manifests_test.yaml
- charts/flux2/values.yaml
Sometimes, accessory to the installation there may be manifest to be installed (for example a SecretProviderClass)
- fixes #71
> feat(flux2): Added ability to deploy extra K8s manifests

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
This PR removes default values for resource.limits. Helm recommends not to specify default resources and to leave this as a conscious choice for the user.
We currently have two issues with default resources:
1. Using CPU limits leads to unnecessary throttling - https://github.com/kubernetes/kubernetes/issues/67577
2. We can not unset the cpu limit key in a sub-chart due to a bug in Helm - https://github.com/helm/helm/issues/9027
Most community helm charts do not set resources but provide guidance with some commented values instead. 
Thanks!
N/A
> Do not set resource limits

- CONTRIBUTING.md
- charts/flux2-sync/Chart.yaml
- charts/flux2-sync/README.md
- charts/flux2-sync/templates/gitrepository.yaml
- charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2/README.md
Update the `apiVersion` for the `GitRepository` resource in the `flux2-sync` chart to `v1beta2`. This api version was released in [source-controller v0.22.0](https://github.com/fluxcd/source-controller/blob/main/CHANGELOG.md#0220) as of 17-MAR-2022.
Fixes: #89
> feat(flux2-sync): update git repository resource to v1beta2

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
Bump to flux2 chart version as a result of the missing update to the readme in a PR prior to #90 
- fixes #
> chore(flux2): bump chart version

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
Signed-off-by: Marco Davalos <marco.davalosmantilla@ravelin.com>
Fix typo in notificationcontroller services annotations.
> Fix typo in notificationcontroller services annotations

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/notification-controller-webhook-service.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
It would be nice to use the port number as targetPort in the webhook service, so the port is added automatically to the firewall rule while running in GCP.
> Use port number in webhook service targetPort

- .github/workflows/release.yml
- .gitignore
- charts/flux2-notification/Chart.yaml
- charts/flux2-notification/README.md
- charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap
- charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap
- charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2-sync/Chart.yaml
- charts/flux2-sync/README.md
- charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
Signed-off-by: Deavon M. McCaffery <dmccaffery@users.noreply.github.com>
Update the release pipeline to publish helm charts to ghcr in addition to GitHub releases.
Closes: #91
> build: update release to push to ghcr

- charts/flux2-sync/Chart.yaml
- charts/flux2-sync/README.md
- charts/flux2-sync/templates/_helpers.tpl
- charts/flux2-sync/templates/generate-git-secret-service-account.yaml
- charts/flux2-sync/templates/generate-git-secret.yaml
- charts/flux2-sync/templates/role.yaml
- charts/flux2-sync/templates/rolebinding.yaml
- charts/flux2-sync/templates/secret.yaml
- charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2-sync/values.yaml
Signed-off-by: ChrisJBurns <29541485+ChrisJBurns@users.noreply.github.com>
Adds automatic Git SSH key generation if configured by user of Chart.
https://github.com/fluxcd-community/helm-charts/issues/101
> Adds Git SSH Key Generation

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/helm-controller.yaml
- charts/flux2/templates/image-automation-controller.yaml
- charts/flux2/templates/image-reflector-controller.yaml
- charts/flux2/templates/kustomize-controller.yaml
- charts/flux2/templates/notification-controller.yaml
- charts/flux2/templates/source-controller.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
This PR adds the ability to specify a `priorityclass` per flux component.
> [Pods](https://kubernetes.io/docs/concepts/workloads/pods/) can have priority. Priority indicates the importance of a Pod relative to other Pods. If a Pod cannot be scheduled, the scheduler tries to preempt (evict) lower priority Pods to make scheduling of the pending Pod possible.
This is useful for flux because in most cases it is more important than other workloads. This PR allows the user to specify a priorityClassName per component.
There is no issue for that.
> feat: add priorityclass

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/podmonitor.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
Signed-off-by: Arcadie Condrat <arcadie.condrat@gmail.com>
Prometheus job generated by the `PodMonitor` does not exclude non-running pods. All the "completed" Pods are going to be  listed as targets in Prometheus and marked as down. This issue is related to `PodMonitor` implementation and is discussed in https://github.com/prometheus-operator/prometheus-operator/issues/4816
N/A
N/A
> Filter out non-running pods in Prometheus

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/helm-controller.yaml
- charts/flux2/templates/image-automation-controller.yaml
- charts/flux2/templates/image-reflector-controller.yaml
- charts/flux2/templates/kustomize-controller.yaml
- charts/flux2/templates/notification-controller.yaml
- charts/flux2/templates/source-controller.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/tests/helm-controller_test.yaml
- charts/flux2/tests/image-automation-controller_test.yaml
- charts/flux2/tests/image-reflector-controller_test.yaml
- charts/flux2/tests/kustomize-controller_test.yaml
- charts/flux2/tests/notification-controller_test.yaml
- charts/flux2/tests/source-controller_test.yaml
- charts/flux2/values.yaml
This PR allows users to select the imagePullPolicy for the controllers.
In most cases it's even recommended to run imagePullPolicy: Always for security reasons.
> feat: add imagePullPolicy to all controllers

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/cluster-reconciler-impersonator-clusterrole.yaml
- charts/flux2/templates/cluster-reconciler-impersonator-clusterrolebinding.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/tests/cluster-reconciler-clusterrolebinding_test.yaml
- charts/flux2/tests/cluster-reconciler-impersonator-clusterrole_test.yaml
- charts/flux2/tests/cluster-reconciler-impersonator-clusterrolebinding.yaml
- charts/flux2/values.yaml
This change aims to add the possibility of both kustomize-controller and helm-controller service accounts to not become cluster-admins.
In Kubernetes Clusters with a very agressive security posture we want to avoid to run service accounts with cluster admin privileges.
If the privileged mode is turned off we will only add service account impersonation capabilities to the kustomize-controller and helm-controller service accounts so they can only impersonate other service accounts that are usually set on the Kustomizations / Helm Releases.
#111
> feat: Add multitenancy privileged mode

- .github/workflows/e2e-sync.yaml
- .github/workflows/lint-test.yaml
- .github/workflows/release.yml
Like in `e2e-sync.yaml`, set the Helm version explicitly for all workflows This is making PRs like https://github.com/fluxcd-community/helm-charts/pull/137 fail because the action is downloading an alpha version
Signed-off-by: Julien Duchesne <julien.duchesne@grafana.com>
> fix(ci): Set Helm version explicitly

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/cluster-reconciler-impersonator-clusterrole.yaml
- charts/flux2/templates/crd-controller-clusterrole.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
We're running with `multitenancy.enabled=true` and `multitenancy.privileged=false`. With 2.x.x we observe the following issue:
```
[...]  helm-controller  reconciliation failed: failed to get last release revision: query: failed to query with labels: 
serviceaccounts "flux-admin" is forbidden: User "system:serviceaccount:flux-system:helm-controller" 
cannot impersonate resource "serviceaccounts" in API group "" in the namespace "admin"
```
This is due to the role pointing to resource `serviceAccount` instead of `serviceaccount`.
N/A
> fix: ensure resource name is all lowercase

- charts/flux2/Chart.yaml
- charts/flux2/templates/helm-controller.crds.yaml
- charts/flux2/templates/image-automation-controller.crds.yaml
- charts/flux2/templates/image-reflector-controller.crds.yaml
- charts/flux2/templates/kustomize-controller.crds.yaml
- charts/flux2/templates/notification-controller.crds.yaml
- charts/flux2/templates/source-controller.crds.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
- hack/generate.sh
Currently, `installCRDs` is a global flag and there's no way to only install CRDs for certain controllers 
This PR adds another level (true by default for retrocompatibility) that can be used to disable CRD installation for a specific controller
> feat: Allow disabling CRDs for specific controllers

- .github/workflows/e2e-sync.yaml
- .github/workflows/lint-test.yaml
- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/helm-controller.yaml
- charts/flux2/templates/image-automation-controller.yaml
- charts/flux2/templates/image-reflector-controller.yaml
- charts/flux2/templates/kustomize-controller.yaml
- charts/flux2/templates/notification-controller.yaml
- charts/flux2/templates/source-controller.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
This PR allows the user to set the `automountServiceAccountToken` in the pod spec. This is a well-known requirement for `CIS`, `BSI` and `NSA` security benchmarks.
The user is supposed to set `serviceAccount.automount=false` and must add the appropriate volumes/volumeMounts.
We probably **shouldn't** set the default to `serviceAccount.automount=false` and provide the necessary volumes/volumeMounts as this would be a breaking change. E.g. if a user supplied a custom `initContainer` this would now be launched without a service account mounted.
-
> feat: allow setting automountServiceAccountToken in pod spec

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/pre-install-job.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/tests/pre-install-job_test.yaml
- charts/flux2/values.yaml
Addresses issue #145
Signed-off-by: Russell Yardley <russell.yardley@finastra.com>
This PR introduces support for specifying annotations for the pre-install-job.  This addresses issue #145.
- fixes #145
> Introduce support for specifying annotations for the pre-install-job

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/helm-controller.yaml
- charts/flux2/templates/image-automation-controller.yaml
- charts/flux2/templates/image-reflector-controller.yaml
- charts/flux2/templates/kustomize-controller.yaml
- charts/flux2/templates/notification-controller.yaml
- charts/flux2/templates/source-controller.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/tests/helm-controller_test.yaml
- charts/flux2/tests/image-automation-controller_test.yaml
- charts/flux2/tests/image-reflector-controller_test.yaml
- charts/flux2/tests/kustomize-controller_test.yaml
- charts/flux2/tests/notification-controller_test.yaml
- charts/flux2/tests/pre-install-job_test.yaml
- charts/flux2/tests/source-controller_test.yaml
Setting the `securityContext` for containers of controller pods is already possible via the `*controller.securityContext` values. This PR allows setting the pod-level `securityContext` via setting the `*controller.podSecurityContext` values.
Note: this naming (`securityContext` and `podSecurityContext`) is in line with how the Kubernetes API is referring to [SecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#securitycontext-v1-core) and [PodSecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#podsecuritycontext-v1-core).
> feat: allow setting PodSecurityContext for controllers

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/pre-install-job.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
* Allow the use of imagePullSecrets in the cli image   (AKA flux-check job) just like all the other containers in the helm chart
- fixes #156
> Allow the use of imagePullSecrets in the cli image

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/helm-controller.yaml
- charts/flux2/templates/image-automation-controller.yaml
- charts/flux2/templates/image-reflector-controller.yaml
- charts/flux2/templates/kustomize-controller.yaml
- charts/flux2/templates/notification-controller.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
Add `extraEnv` helm value setting for all flux controllers. source-controller already has this. this change exposes the same across all controllers consistently.
In case of using kubeconfig reference in HelmReleases or Kustomizations to reconcile on remote clusters, and in such setups where Kubernetes API endpoints of those remote clusters could require going through an egress proxy for reachability.
> Support extraEnv value setting for all flux controllers

- Makefile
- charts/flux2-notification/Chart.yaml
- charts/flux2-notification/README.md
- charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap
- charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap
- charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2-sync/Chart.yaml
- charts/flux2-sync/README.md
- charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap
- charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2-sync/values.yaml
- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/helm-controller.crds.yaml
- charts/flux2/templates/image-automation-controller.crds.yaml
- charts/flux2/templates/image-reflector-controller.crds.yaml
- charts/flux2/templates/kustomize-controller.crds.yaml
- charts/flux2/templates/notification-controller.crds.yaml
- charts/flux2/templates/source-controller.crds.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
- hack/generate.sh
- Upgrades the helm charts to use the Flux2 v2.0.1 release.
- fixes #
> chore: upgrade charts to Flux v2.0.1 release

- Makefile
- charts/flux2-notification/Chart.yaml
- charts/flux2-notification/README.md
- charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap
- charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap
- charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2-sync/Chart.yaml
- charts/flux2-sync/README.md
- charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap
- charts/flux2-sync/tests/__snapshot__/flux-kustomization_test.yaml.snap
- charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2-sync/values.yaml
- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
- Upgrades the helm charts to use the Flux2 v2.1.1 release.
- fixes #
> chore: upgrade charts to Flux v2.1.1 release

- .github/workflows/codespell.yaml
- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
Currently imagePullPolicy is marked as an `object`. It should be a `string`.
- fixes #
> Fix imagePullPolicy schema

- .github/workflows/lint-test.yaml
- CONTRIBUTING.md
- Makefile
- ct.yaml
--helm3 does not exist anymore
- fixes #196
> Remove --helm3 flag from unittest

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/helm-controller-sa.yaml
- charts/flux2/templates/helm-controller.crds.yaml
- charts/flux2/templates/helm-controller.yaml
- charts/flux2/templates/image-automation-controller-sa.yaml
- charts/flux2/templates/image-automation-controller.crds.yaml
- charts/flux2/templates/image-automation-controller.yaml
- charts/flux2/templates/image-reflector-controller-sa.yaml
- charts/flux2/templates/image-reflector-controller.crds.yaml
- charts/flux2/templates/image-reflector-controller.yaml
- charts/flux2/templates/kustomize-controller-sa.yaml
- charts/flux2/templates/kustomize-controller.crds.yaml
- charts/flux2/templates/kustomize-controller.yaml
- charts/flux2/templates/notification-controller-sa.yaml
- charts/flux2/templates/notification-controller.yaml
- charts/flux2/templates/source-controller-serviceaccount.yaml
- charts/flux2/templates/source-controller.crds.yaml
- charts/flux2/templates/source-controller.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
`flux` cli assigns `app.kubernetes.io/component` labels to the component controllers. This pr does the same when installed using helm chart.
- fixes #
- [c] Update artifacthub.io/changes in Chart.yaml
> Add `app.kubernetes.io/component` label to flux controllers

- .github/workflows/lint-test.yaml
- _readme_templates.gotmpl
- charts/flux2-multi-tenancy/Chart.yaml
- charts/flux2-multi-tenancy/README.md
- charts/flux2-multi-tenancy/tests/__snapshot__/kyverno-policy_test.yaml.snap
- charts/flux2-notification/Chart.yaml
- charts/flux2-notification/README.md
- charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap
- charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap
- charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2-sync/Chart.yaml
- charts/flux2-sync/README.md
- charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap
- charts/flux2-sync/tests/__snapshot__/flux-kustomization_test.yaml.snap
- charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/notification-controller-ingress.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
Ingress resource for notificationController's receiver webhook service
Used values for testing:
```
notificationController:
webhookReceiver:
ingress:
create: true
ingressClassName: nginx
annotations:
kubernetes.io/ingress.class: nginx
kubernetes.io/tls-acme: "true"
hosts:
- host: flux-webhook.example.com
paths:
- path: /
pathType: ImplementationSpecific
tls:
- secretName: flux-webhook-tls
hosts:
- flux-webhook.example.com
```
- fixes #128 
- superseds #163
- superseds #169
> feat(flux2): add webhook-receiver ingress

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/aggregate-clusterroles.yaml
- charts/flux2/templates/cluster-reconciler-clusterrolebinding.yaml
- charts/flux2/templates/cluster-reconciler-impersonator-clusterrole.yaml
- charts/flux2/templates/cluster-reconciler-impersonator-clusterrolebinding.yaml
- charts/flux2/templates/crd-controller-clusterrole.yaml
- charts/flux2/templates/crd-controller-clusterrolebinding.yaml
- charts/flux2/templates/helm-controller.crds.yaml
- charts/flux2/templates/image-automation-controller.crds.yaml
- charts/flux2/templates/image-reflector-controller.crds.yaml
- charts/flux2/templates/kustomize-controller.crds.yaml
- charts/flux2/templates/notification-controller.crds.yaml
- charts/flux2/templates/source-controller.crds.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/tests/cluster-reconciler-clusterrolebinding_test.yaml
- charts/flux2/tests/cluster-reconciler-impersonator-clusterrole_test.yaml
- charts/flux2/tests/cluster-reconciler-impersonator-clusterrolebinding.yaml
- charts/flux2/values.yaml
Adding annotations to CRD and RBAC resources. This helps to keep those resources in cases where `installCRDs: false` or `rbac.create: false` will take effect on `helm update`.
- fixes #
> Adding CRD and RBAC annotation option

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/source-controller.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
https://github.com/fluxcd/source-controller/issues/837#issuecomment-1228118085
We scaled all deployments of this HelmChart up to 2 replicas and the source-controller started failing. It would make more sense to not allow this, because there seems to be no way to make this work.
The `replicas` key is not present in the values.yaml (for any of the components) - in case you are wondering, why there is no change to the `values.yaml`.
- didn't change anything
- I reverted the changes it would have made to other parts; I only want to update flux2
> fix(charts,flux2,source-controller): hard-code replicas

- Makefile
- charts/flux2-notification/Chart.yaml
- charts/flux2-notification/README.md
- charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap
- charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap
- charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2-sync/Chart.yaml
- charts/flux2-sync/README.md
- charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap
- charts/flux2-sync/tests/__snapshot__/flux-kustomization_test.yaml.snap
- charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2-sync/values.yaml
- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/helm-controller.crds.yaml
- charts/flux2/templates/notification-controller.crds.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
- Upgrades the helm charts to use the Flux2 v2.2.2 release.
- fixes #
> chore: upgrade charts to Flux v2.2.2 release

- Makefile
- charts/flux2-notification/Chart.yaml
- charts/flux2-notification/README.md
- charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap
- charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap
- charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2-sync/Chart.yaml
- charts/flux2-sync/README.md
- charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap
- charts/flux2-sync/tests/__snapshot__/flux-kustomization_test.yaml.snap
- charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2-sync/values.yaml
- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/notification-controller.crds.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
- hack/generate.sh
- Upgrades the helm charts to use the Flux2 v2.2.3 release.
NA
> chore: upgrade charts to Flux v2.2.3 release

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/cluster-reconciler-clusterrolebinding.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/tests/cluster-reconciler-clusterrolebinding_test.yaml
- charts/flux2/values.yaml
Users should be able to assign a lower-scope ClusterRole to the reconciler which does not have full cluster admin privileges. This PR replaces the hardcoded name with a value
> Make cluster role name configurable

- .github/workflows/codespell.yaml
- Makefile
- charts/flux2-notification/Chart.yaml
- charts/flux2-notification/README.md
- charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap
- charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap
- charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2-sync/Chart.yaml
- charts/flux2-sync/README.md
- charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap
- charts/flux2-sync/tests/__snapshot__/flux-kustomization_test.yaml.snap
- charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2-sync/values.yaml
- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/helm-controller.crds.yaml
- charts/flux2/templates/image-automation-controller.crds.yaml
- charts/flux2/templates/image-reflector-controller.crds.yaml
- charts/flux2/templates/kustomize-controller.crds.yaml
- charts/flux2/templates/notification-controller.crds.yaml
- charts/flux2/templates/source-controller.crds.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
Upgrade to Flux 2.4.0.
- Changes:
- version in Makefile
- artifacthub.io/changes
- chart versions (flux2, flux2-notification, flux2-sync)
- other changed by `make`
- Tested on:
- upgrade from previous
- new release
- To be sure, I compared the diff of commit with previous similar ones (to 2.2.3, to 2.3.0, etc.) and same files are changed in same way
We already use it on (not small) production infrastructure because we need Flux 2.4.0.
@stefanprodan I am glad to cooperate, probably in the future I will send some PR to discussion / overall improving of Helm chart.
> chore: upgrade charts to Flux v2.4.0 release

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/helm-controller.crds.yaml
- charts/flux2/templates/image-automation-controller.crds.yaml
- charts/flux2/templates/image-reflector-controller.crds.yaml
- charts/flux2/templates/kustomize-controller.crds.yaml
- charts/flux2/templates/notification-controller.crds.yaml
- charts/flux2/templates/source-controller.crds.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- hack/generate.sh
In the flux2 helm chart there is already the possibility to set the value `crds.annotations`. Unfortunately, this value is not used anywhere because the corresponding templates are missing in the crds. With this merge request I want to add templating to the generated crds so that this value can not only be set without meaning, but also so that the annotations in the crds can actually be customised.
- didn't change anything
> fix(charts/flux2,crds): crds.annotations got respected now

- .github/workflows/e2e-sync.yaml
- .github/workflows/lint-test.yaml
- Makefile
- charts/flux2-notification/Chart.yaml
- charts/flux2-notification/README.md
- charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap
- charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap
- charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2-sync/Chart.yaml
- charts/flux2-sync/README.md
- charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap
- charts/flux2-sync/tests/__snapshot__/flux-kustomization_test.yaml.snap
- charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap
- charts/flux2-sync/values.yaml
- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/helm-controller.crds.yaml
- charts/flux2/templates/image-automation-controller.crds.yaml
- charts/flux2/templates/kustomize-controller.crds.yaml
- charts/flux2/templates/notification-controller.crds.yaml
- charts/flux2/templates/source-controller.crds.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
- Upgrades the helm charts to use the Flux2 v2.5.1 release.
> chore: upgrade charts to Flux v2.5.1 release

- charts/flux2/Chart.yaml
- charts/flux2/README.md
- charts/flux2/templates/image-automation-controller.yaml
- charts/flux2/templates/image-reflector-controller.yaml
- charts/flux2/templates/kustomize-controller.yaml
- charts/flux2/templates/openshift.yaml
- charts/flux2/templates/source-controller.yaml
- charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap
- charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap
- charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap
- charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
- charts/flux2/values.yaml
Add support to deploy in OpenShift cluster. It does 2 things
(1) Add scc as recommended here: https://fluxcd.io/flux/installation/configuration/openshift/
(2) Stop's setting runAsUser in OpenShift mode which allows OpenShift to automatically set the correct uid via mutating webhook.
- fixes #
> feat(flux2): support deploying to openshift
