.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/codespell.yaml, .github/workflows/lint-test.yaml, .github/workflows/release.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, ct.yaml
* add codespell workflow
* add chart-testing action
* add documentation and PR template
=> add codespell workflow (#1)

charts/flux2/Chart.yaml, charts/flux2/values.yaml, ct.yaml
* update image download source to use ghcr.io
* remove helm maintainers validation, because this entry is optional and as community chart there is no specific maintern right now
- fixes #7
=> update image download source to use ghcr.io

.github/PULL_REQUEST_TEMPLATE.md, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/helm-controller.yaml, charts/flux2/templates/image-automation-controller.yaml, charts/flux2/templates/image-reflector-controller.yaml, charts/flux2/templates/kustomize-controller.yaml, charts/flux2/templates/notification-controller.yaml, charts/flux2/templates/source-controller.yaml, charts/flux2/values.yaml
Its possible to add nodeSelector, affinity and tolerations to the deployments via values.
=> extend values for nodeselctor, affinity and tolerations

.github/workflows/e2e-sync.yaml, .github/workflows/e2e.yaml, .github/workflows/lint-test.yaml, charts/flux2-sync/Chart.yaml, charts/flux2-sync/README.md, charts/flux2-sync/templates/gitrepository.yaml, charts/flux2-sync/templates/kustomization.yaml, charts/flux2-sync/values.yaml
This PR adds basic e2e tests for the flux2-sync chart. It also comes with various fixes and breaking changes to flux2-sync.
Fix: #22
=> Add end-to-end tests and various fixes to flux2-sync chart

charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/pre-install-job.yaml, charts/flux2/values.yaml
Signed-off-by: Marc Normann <marc.normann@extern.dkbcodefactory.com>
This PR will add a Pre- and Post-Install Hook for Flux to run job _flux check --pre_
- fixes #18
=> Added Pre- and Post-Install Hook

Makefile, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/image-automation-controller-crds.yaml, charts/flux2/templates/image-reflector-controller-crds.yaml, charts/flux2/templates/notification-controller-crds.yaml, charts/flux2/templates/source-controller-crds.yaml
upgrade CRDS for 0.24.0 release
- followup for https://github.com/fluxcd-community/helm-charts/pull/29
=> fix crds for 0.24.0 release

charts/flux2-sync/Chart.yaml, charts/flux2-sync/templates/gitrepository.yaml, charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap
- fixed small issue in secretRef use .Release.Name
- fixes #
=> fix(sec): fix secret name ref in flux2-sync

.pre-commit-config.yaml
added pre-commit-config
to run generate & helmdocs step for each commit
```
git commit -sm "feat(pre-commit) added pre-commit"
generate.................................................................Passed
helmdocs.................................................................Passed
[feature/pre-commit 406b375] feat(pre-commit) added pre-commit
```
=> feat(pre-commit) added pre-commit

charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/source-controller.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
=> Add value sourcecontroller.extraEnv

charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/helm-controller.yaml, charts/flux2/templates/image-automation-controller.yaml, charts/flux2/templates/image-reflector-controller.yaml, charts/flux2/templates/kustomize-controller.yaml, charts/flux2/templates/notification-controller.yaml, charts/flux2/templates/source-controller.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/tests/helm-controller_test.yaml, charts/flux2/tests/image-automation-controller_test.yaml, charts/flux2/tests/image-reflector-controller_test.yaml, charts/flux2/tests/kustomize-controller_test.yaml, charts/flux2/tests/notification-controller_test.yaml, charts/flux2/tests/source-controller_test.yaml, charts/flux2/values.yaml
Signed-off-by: Oleg Tsymbal <dzirg44@gmail.com>
Add additional command line arguments across all containers in order to use new commands
- fixes #69
=> Add additional args to controllers

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/source-controller.crds.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
=> feature(update) update to AppVersion 0.26.2

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
=> feature(update) update to AppVersion 0.26.3

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/helm-controller.crds.yaml, charts/flux2/templates/kustomize-controller.crds.yaml, charts/flux2/templates/notification-controller.crds.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
=> feature(update) update to AppVersion 0.27.0

charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/notification-controller.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
Signed-off-by: steveizzle <stefan.riembauer@gmail.com>
This PR fixes the template for notificationController. There is a reference to helmController. If this is really intentionally please close this PR!
- fixes #
=> Fixed SecurityContext in notificaitonController Template

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/helm-controller.crds.yaml, charts/flux2/templates/image-automation-controller.crds.yaml, charts/flux2/templates/image-reflector-controller.crds.yaml, charts/flux2/templates/kustomize-controller.crds.yaml, charts/flux2/templates/notification-controller.crds.yaml, charts/flux2/templates/source-controller.crds.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
Signed-off-by: Daniel Werdermann <daniel.werdermann@dkb.de>
Update to upstream App 0.28.3
=> feature(update) update to AppVersion 0.28.3

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/helm-controller.crds.yaml, charts/flux2/templates/kustomize-controller.crds.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
Updates to Flux [v0.29.x](https://github.com/fluxcd/flux2/releases/v0.29.0).
This might require some additional work, especially because sets of flags have been introduced in some controllers. In addition, we might want to bump a minor version instead, as some controllers contain breaking behavior changes (see release notes).
=> feature(update) update to AppVersion 0.29.1

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
=> feature(update) update to AppVersion 0.29.2

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
=> feature(update) update to AppVersion 0.29.3

charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/notification-controller-service.yaml, charts/flux2/templates/notification-controller-webhook-service.yaml, charts/flux2/templates/source-controller-service.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
Allows you to set additional custom annotations and labels to all the services in the chart.
=> Allow custom labels and annotations for all services

hack/generate.sh
`make generate` updates the docker image tags in values.yaml and the unittests snapshots
- fixes #47 
Nothing changed on the helm charts.
=> feature(generate) generate imageTags for all controller from upstream

charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap
Trigger helm release. Real commit was done here: https://github.com/fluxcd-community/helm-charts/commit/e969eb147099e35af1b27a807789f546bd5b7e1c
I accidentally pushed directly to master.
- fixes #92
=> Update to 0.30.2

.gitignore, Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/Chart.yaml, charts/flux2-sync/README.md, charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/values.yaml, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
- Update appversion to flux 0.31.3
- Start with helm chart version 1.x
- fixes #62
=> feature(update) update to AppVersion 0.31.3

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/kustomize-controller.crds.yaml, charts/flux2/templates/notification-controller.crds.yaml, charts/flux2/templates/source-controller.crds.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
- Update appVersion to flux 0.32.0
- fixes #114
=> feature(update) update to AppVersion 0.32.0

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/helm-controller.crds.yaml, charts/flux2/templates/image-automation-controller.crds.yaml, charts/flux2/templates/image-reflector-controller.crds.yaml, charts/flux2/templates/kustomize-controller.crds.yaml, charts/flux2/templates/notification-controller.crds.yaml, charts/flux2/templates/source-controller.crds.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
Signed-off-by: Jamie Hitchen <jamie.hitchen@digiidnet.co.uk>
- Update Flux appVersion to v0.33.0
- Resolves #117
=> feat(update): update to AppVersion 0.33.0

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/helm-controller.crds.yaml, charts/flux2/templates/image-automation-controller.crds.yaml, charts/flux2/templates/image-reflector-controller.crds.yaml, charts/flux2/templates/kustomize-controller.crds.yaml, charts/flux2/templates/notification-controller.crds.yaml, charts/flux2/templates/source-controller.crds.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
- update flux version to [0.34.0](https://github.com/fluxcd/flux2/releases/tag/v0.34.0)
- close #122
=> chore(update) update to AppVersion 0.34.0

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/helm-controller.crds.yaml, charts/flux2/templates/image-automation-controller.crds.yaml, charts/flux2/templates/image-reflector-controller.crds.yaml, charts/flux2/templates/kustomize-controller.crds.yaml, charts/flux2/templates/notification-controller.crds.yaml, charts/flux2/templates/source-controller.crds.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
Signed-off-by: Julien Duchesne <julien.duchesne@grafana.com>
update flux version to [0.35.0](https://github.com/fluxcd/flux2/releases/tag/v0.35.0)
=> chore(update) update to AppVersion 0.35.0

charts/flux2-sync/Chart.yaml, charts/flux2-sync/README.md, charts/flux2-sync/templates/flux-gitrepository.yaml, charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/values.yaml
Signed-off-by: Jan Nabbefeld <jan@odise.de>
- fixes #133
=> fixing .Values.gitRepository.spec.ignore to support multiline strings

charts/flux2-sync/Chart.yaml, charts/flux2-sync/README.md, charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/tests/flux-gitrepository_test.yaml, charts/flux2-sync/values.yaml
- add unittests for flux-gitrepository
=> chore(tests) add unittests for flux-gitrepository

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/Chart.yaml, charts/flux2-sync/README.md, charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/helm-controller.crds.yaml, charts/flux2/templates/kustomize-controller.crds.yaml, charts/flux2/templates/notification-controller.crds.yaml, charts/flux2/templates/source-controller.crds.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
Closes https://github.com/fluxcd-community/helm-charts/issues/136
Signed-off-by: Julien Duchesne <julien.duchesne@grafana.com>
=> chore(update) update to AppVersion 0.36.0

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/Chart.yaml, charts/flux2-sync/README.md, charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/values.yaml, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/kustomize-controller.crds.yaml, charts/flux2/templates/notification-controller.crds.yaml, charts/flux2/templates/source-controller.crds.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml, hack/generate.sh
Signed-off-by: Julien Duchesne <julien.duchesne@grafana.com>
Fix: #161 
Fix: #151
=> chore(update) update to AppVersion 0.39.0

charts/flux2-sync/Chart.yaml, charts/flux2-sync/README.md, charts/flux2-sync/templates/flux-gitrepository.yaml, charts/flux2-sync/templates/flux-kustomization.yaml, charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/values.yaml
Allows users of the helm chart to be able to add labels and annotations to the custom resources
=> Add labels and annotions to custom resources

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/Chart.yaml, charts/flux2-sync/README.md, charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/values.yaml, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/aggregate-clusterroles.yaml, charts/flux2/templates/helm-controller.crds.yaml, charts/flux2/templates/image-automation-controller.crds.yaml, charts/flux2/templates/image-reflector-controller.crds.yaml, charts/flux2/templates/kustomize-controller.crds.yaml, charts/flux2/templates/notification-controller.crds.yaml, charts/flux2/templates/source-controller.crds.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
Signed-off-by: toVersus <toversus2357@gmail.com>
* Update image tags for Flux2 components and CRD schema
* Add option to grant the Kubernetes view, edit and admin roles access to Flux custom resources
- fixes #164
=> chore(update): update to AppVersion 0.41.1

charts/flux2-sync/Chart.yaml, charts/flux2-sync/README.md, charts/flux2-sync/templates/flux-kustomization.yaml, charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/flux-kustomization_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/tests/flux-kustomization_test.yaml
kubeconfig change if to with in template to make it possible to generate
- fixes #
=> fix(ks): kubeconfig change if to with in template

charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/templates/provider.yaml, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-notification/values.yaml
=> flux2-notification: fix provider template

.github/workflows/lint-test.yaml, charts/flux2-multi-tenancy/Chart.yaml, charts/flux2-multi-tenancy/README.md, charts/flux2-multi-tenancy/tests/__snapshot__/kyverno-policy_test.yaml.snap, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/pre-install-job-serviceaccount.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/tests/pre-install-job_test.yaml
=> Fix unittest snapshot file indentation

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/Chart.yaml, charts/flux2-sync/README.md, charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/flux-kustomization_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
Update to Flux 2.1.2
- fixes #
=> Update to Flux 2.1.2

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/Chart.yaml, charts/flux2-sync/README.md, charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/flux-kustomization_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/values.yaml, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/templates/helm-controller.crds.yaml, charts/flux2/templates/image-automation-controller.crds.yaml, charts/flux2/templates/image-reflector-controller.crds.yaml, charts/flux2/templates/kustomize-controller.crds.yaml, charts/flux2/templates/notification-controller.crds.yaml, charts/flux2/templates/source-controller.crds.yaml, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
=> chore: upgrade charts to Flux v2.3.0 release

charts/flux2-sync/Chart.yaml, charts/flux2-sync/README.md, charts/flux2-sync/templates/flux-gitrepository.yaml, charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/flux-kustomization_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/values.yaml
=> feat(flux2-sync): Add gitRepository provider option

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/Chart.yaml, charts/flux2-sync/README.md, charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/flux-kustomization_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/values.yaml, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
=> [Chore]: Update App Version to upstream 2.6.2

Makefile, charts/flux2-notification/Chart.yaml, charts/flux2-notification/README.md, charts/flux2-notification/tests/__snapshot__/alert_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/provider_test.yaml.snap, charts/flux2-notification/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/Chart.yaml, charts/flux2-sync/README.md, charts/flux2-sync/tests/__snapshot__/flux-gitrepository_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/flux-kustomization_test.yaml.snap, charts/flux2-sync/tests/__snapshot__/secret_test.yaml.snap, charts/flux2-sync/values.yaml, charts/flux2/Chart.yaml, charts/flux2/README.md, charts/flux2/tests/__snapshot__/helm-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-automation-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/image-reflector-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller-secret_test.yaml.snap, charts/flux2/tests/__snapshot__/kustomize-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/notification-controller_test.yaml.snap, charts/flux2/tests/__snapshot__/pre-install-job_test.yaml.snap, charts/flux2/tests/__snapshot__/source-controller_test.yaml.snap, charts/flux2/values.yaml
Update App Version to upstream 2.6.4 
- fixes #
We use the helm chart to deploy Flux, and would like to update the application urgently 
We followed the last update as an example:
https://github.com/fluxcd-community/helm-charts/commit/66c1e60c155a75de6f2ff6b8d2dd8054778efffe
We tested the update using > make unittests 
Charts:      1 passed, 1 total
Test Suites: 6 passed, 6 total
Tests:       14 passed, 14 total
Snapshot:    6 passed, 6 total
Time:        35.949199ms
Apologies if this PR does not follow your expectations; it is our first contribution, and we tried to follow the guidelines as close as possible.
=> Update App Version to upstream 2.6.4 
